### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by sshawn9** [Magic-wei/make_work_easier#4]
https://github.com/Magic-wei/make_work_easier/blob/cd0e181cb0fd0b9636f879167dcfed4ff73824d7/README.md?plain=1#L93

`But ff you are merely working on structured data analysis`

typo error in second word

**Comment by Magic-wei** [comment]
Fixed in commit [cdfab6b](https://github.com/Magic-wei/make_work_easier/commit/cdfab6bd3c8edb60d814990acf4b38e97203be49).
